# Generated by Django 3.0.3 on 2020-02-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_info', models.CharField(max_length=255)),
                ('browser_info', models.CharField(max_length=255)),
                ('request_data', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=20)),
                ('event_name', models.CharField(max_length=255)),
                ('visited_by', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
