# Generated by Django 3.0.3 on 2020-02-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event_name',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='log',
            name='method',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='log',
            name='path_info',
            field=models.CharField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='log',
            name='request_data',
            field=models.CharField(max_length=2047),
        ),
    ]
