# Generated by Django 3.0.3 on 2020-03-01 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20200223_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='location',
            new_name='location_city',
        ),
        migrations.AddField(
            model_name='log',
            name='location_country',
            field=models.CharField(default=datetime.datetime(2020, 3, 1, 21, 22, 39, 178821), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='location_region',
            field=models.CharField(default=datetime.datetime(2020, 3, 1, 21, 22, 46, 846675), max_length=255),
            preserve_default=False,
        ),
    ]
